name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 16
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '16'
      - name: class member count (1 point)
        id: class-member-count-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: class member count (1 point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.classMembersCountReflection
          timeout: 2
          max-score: 1
      - name: union2 (1 Point)
        id: union2-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: union2 (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.union2
          timeout: 1
          max-score: 1
      - name: Constructors (2 Points)
        id: constructors-2-points
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Constructors (2 Points)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.classConstructorsReflection
          timeout: 1
          max-score: 2
      - name: getWidth (1 Point)
        id: getwidth-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: getWidth (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.getWidth
          timeout: 1
          max-score: 1
      - name: getHeight (1 Point)
        id: getheight-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: getHeight (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.getHeight
          timeout: 1
          max-score: 1
      - name: getCount (1 Point)
        id: getcount-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: getCount (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.getCount
          timeout: 1
          max-score: 1
      - name: Point isInside (1 Point)
        id: point-isinside-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Point isInside (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.isInside1
          timeout: 1
          max-score: 1
      - name: Rectangle isInside (1 Point)
        id: rectangle-isinside-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Rectangle isInside (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.isInside2
          timeout: 1
          max-score: 1
      - name: toString (1 Point)
        id: tostring-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: toString (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.rectangleToString
          timeout: 1
          max-score: 1
      - name: union1 (1 Point)
        id: union1-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: union1 (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.union1
          timeout: 1
          max-score: 1
      - name: union2
        id: union2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: union2
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.union2
          timeout: 1
          max-score: 1
      - name: intersection1 (1 Point)
        id: intersection1-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: intersection1 (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.intersection1
          timeout: 1
          max-score: 1
      - name: intersection2 (1 Point)
        id: intersection2-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: intersection2 (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.intersection2
          timeout: 1
          max-score: 1
      - name: generateRectangles (1 Point)
        id: generaterectangles-1-point
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: generateRectangles (1 Point)
          setup-command: ''
          command: gradle test --tests at.ac.fhcampuswien.AppTest.generateRectangles
          timeout: 1
          max-score: 1
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CLASS-MEMBER-COUNT-1-POINT_RESULTS: "${{steps.class-member-count-1-point.outputs.result}}"
          UNION2-1-POINT_RESULTS: "${{steps.union2-1-point.outputs.result}}"
          CONSTRUCTORS-2-POINTS_RESULTS: "${{steps.constructors-2-points.outputs.result}}"
          GETWIDTH-1-POINT_RESULTS: "${{steps.getwidth-1-point.outputs.result}}"
          GETHEIGHT-1-POINT_RESULTS: "${{steps.getheight-1-point.outputs.result}}"
          GETCOUNT-1-POINT_RESULTS: "${{steps.getcount-1-point.outputs.result}}"
          POINT-ISINSIDE-1-POINT_RESULTS: "${{steps.point-isinside-1-point.outputs.result}}"
          RECTANGLE-ISINSIDE-1-POINT_RESULTS: "${{steps.rectangle-isinside-1-point.outputs.result}}"
          TOSTRING-1-POINT_RESULTS: "${{steps.tostring-1-point.outputs.result}}"
          UNION1-1-POINT_RESULTS: "${{steps.union1-1-point.outputs.result}}"
          UNION2_RESULTS: "${{steps.union2.outputs.result}}"
          INTERSECTION1-1-POINT_RESULTS: "${{steps.intersection1-1-point.outputs.result}}"
          INTERSECTION2-1-POINT_RESULTS: "${{steps.intersection2-1-point.outputs.result}}"
          GENERATERECTANGLES-1-POINT_RESULTS: "${{steps.generaterectangles-1-point.outputs.result}}"
        with:
          runners: class-member-count-1-point,union2-1-point,constructors-2-points,getwidth-1-point,getheight-1-point,getcount-1-point,point-isinside-1-point,rectangle-isinside-1-point,tostring-1-point,union1-1-point,union2,intersection1-1-point,intersection2-1-point,generaterectangles-1-point
